// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	nexxa "github.com/aussenseiter-VsRB/JHIC-BE/internal/domain/nexxa"
	mock "github.com/stretchr/testify/mock"
)

// N8NClient is an autogenerated mock type for the N8NClient type
type N8NClient struct {
	mock.Mock
}

// Chat provides a mock function with given fields: ctx, chatInput, sessionID
func (_m *N8NClient) Chat(ctx context.Context, chatInput string, sessionID string) (*nexxa.ChatResponse, error) {
	ret := _m.Called(ctx, chatInput, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Chat")
	}

	var r0 *nexxa.ChatResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*nexxa.ChatResponse, error)); ok {
		return rf(ctx, chatInput, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *nexxa.ChatResponse); ok {
		r0 = rf(ctx, chatInput, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nexxa.ChatResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, chatInput, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CvReview provides a mock function with given fields: ctx, cvText, wordCount, pageCount
func (_m *N8NClient) CvReview(ctx context.Context, cvText string, wordCount int, pageCount int) (string, error) {
	ret := _m.Called(ctx, cvText, wordCount, pageCount)

	if len(ret) == 0 {
		panic("no return value specified for CvReview")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) (string, error)); ok {
		return rf(ctx, cvText, wordCount, pageCount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) string); ok {
		r0 = rf(ctx, cvText, wordCount, pageCount)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, cvText, wordCount, pageCount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NexxaMatch provides a mock function with given fields: ctx, answers
func (_m *N8NClient) NexxaMatch(ctx context.Context, answers []string) (string, error) {
	ret := _m.Called(ctx, answers)

	if len(ret) == 0 {
		panic("no return value specified for NexxaMatch")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (string, error)); ok {
		return rf(ctx, answers)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) string); ok {
		r0 = rf(ctx, answers)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, answers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewN8NClient creates a new instance of N8NClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewN8NClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *N8NClient {
	mock := &N8NClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
