// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	id "github.com/aussenseiter-VsRB/JHIC-BE/internal/pkg/id"
	mock "github.com/stretchr/testify/mock"

	spmb "github.com/aussenseiter-VsRB/JHIC-BE/internal/domain/spmb"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// ByID provides a mock function with given fields: ctx, _a1
func (_m *Repository) ByID(ctx context.Context, _a1 id.ID) (*spmb.SpmbRegistration, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 *spmb.SpmbRegistration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, id.ID) (*spmb.SpmbRegistration, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, id.ID) *spmb.SpmbRegistration); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*spmb.SpmbRegistration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, id.ID) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, r
func (_m *Repository) Create(ctx context.Context, r *spmb.SpmbRegistration) error {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *spmb.SpmbRegistration) error); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListAll provides a mock function with given fields: ctx
func (_m *Repository) ListAll(ctx context.Context) ([]spmb.SpmbRegistration, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []spmb.SpmbRegistration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]spmb.SpmbRegistration, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []spmb.SpmbRegistration); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]spmb.SpmbRegistration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, r, expectedStatus
func (_m *Repository) UpdateStatus(ctx context.Context, r *spmb.SpmbRegistration, expectedStatus string) error {
	ret := _m.Called(ctx, r, expectedStatus)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *spmb.SpmbRegistration, string) error); ok {
		r0 = rf(ctx, r, expectedStatus)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
