// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	ai "github.com/aussenseiter-VsRB/JHIC-BE/internal/domain/ai"
)

// N8NClient is an autogenerated mock type for the N8NClient type
type N8NClient struct {
	mock.Mock
}

// Chat provides a mock function with given fields: ctx, chatInput, sessionID
func (_m *N8NClient) Chat(ctx context.Context, chatInput string, sessionID string) (*ai.ChatResponse, error) {
	ret := _m.Called(ctx, chatInput, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Chat")
	}

	var r0 *ai.ChatResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*ai.ChatResponse, error)); ok {
		return rf(ctx, chatInput, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *ai.ChatResponse); ok {
		r0 = rf(ctx, chatInput, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ai.ChatResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, chatInput, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NexxaMatch provides a mock function with given fields: ctx, answers
func (_m *N8NClient) NexxaMatch(ctx context.Context, answers []string) (*ai.NexxaResponse, error) {
	ret := _m.Called(ctx, answers)

	if len(ret) == 0 {
		panic("no return value specified for NexxaMatch")
	}

	var r0 *ai.NexxaResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (*ai.NexxaResponse, error)); ok {
		return rf(ctx, answers)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) *ai.NexxaResponse); ok {
		r0 = rf(ctx, answers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ai.NexxaResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, answers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewN8NClient creates a new instance of N8NClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewN8NClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *N8NClient {
	mock := &N8NClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
