// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	pkl "github.com/aussenseiter-VsRB/JHIC-BE/internal/domain/pkl"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// ByID provides a mock function with given fields: ctx, id
func (_m *Repository) ByID(ctx context.Context, id string) (*pkl.PklRequest, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 *pkl.PklRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*pkl.PklRequest, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *pkl.PklRequest); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pkl.PklRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Cancel provides a mock function with given fields: ctx, req
func (_m *Repository) Cancel(ctx context.Context, req *pkl.PklRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *pkl.PklRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateRequest provides a mock function with given fields: ctx, req, steps
func (_m *Repository) CreateRequest(ctx context.Context, req *pkl.PklRequest, steps []pkl.Step) error {
	ret := _m.Called(ctx, req, steps)

	if len(ret) == 0 {
		panic("no return value specified for CreateRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *pkl.PklRequest, []pkl.Step) error); ok {
		r0 = rf(ctx, req, steps)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Decide provides a mock function with given fields: ctx, req, step, expectedReqStatus, expectedStepStatus
func (_m *Repository) Decide(ctx context.Context, req *pkl.PklRequest, step *pkl.Step, expectedReqStatus string, expectedStepStatus string) error {
	ret := _m.Called(ctx, req, step, expectedReqStatus, expectedStepStatus)

	if len(ret) == 0 {
		panic("no return value specified for Decide")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *pkl.PklRequest, *pkl.Step, string, string) error); ok {
		r0 = rf(ctx, req, step, expectedReqStatus, expectedStepStatus)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListAll provides a mock function with given fields: ctx
func (_m *Repository) ListAll(ctx context.Context) ([]pkl.PklRequest, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []pkl.PklRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]pkl.PklRequest, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []pkl.PklRequest); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pkl.PklRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByRequester provides a mock function with given fields: ctx, requesterID
func (_m *Repository) ListByRequester(ctx context.Context, requesterID string) ([]pkl.PklRequest, error) {
	ret := _m.Called(ctx, requesterID)

	if len(ret) == 0 {
		panic("no return value specified for ListByRequester")
	}

	var r0 []pkl.PklRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]pkl.PklRequest, error)); ok {
		return rf(ctx, requesterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []pkl.PklRequest); ok {
		r0 = rf(ctx, requesterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pkl.PklRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, requesterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListForApprover provides a mock function with given fields: ctx, approverID
func (_m *Repository) ListForApprover(ctx context.Context, approverID string) ([]pkl.PklRequest, error) {
	ret := _m.Called(ctx, approverID)

	if len(ret) == 0 {
		panic("no return value specified for ListForApprover")
	}

	var r0 []pkl.PklRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]pkl.PklRequest, error)); ok {
		return rf(ctx, approverID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []pkl.PklRequest); ok {
		r0 = rf(ctx, approverID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pkl.PklRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, approverID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StepsByRequest provides a mock function with given fields: ctx, requestID
func (_m *Repository) StepsByRequest(ctx context.Context, requestID string) ([]pkl.Step, error) {
	ret := _m.Called(ctx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for StepsByRequest")
	}

	var r0 []pkl.Step
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]pkl.Step, error)); ok {
		return rf(ctx, requestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []pkl.Step); ok {
		r0 = rf(ctx, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pkl.Step)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, requestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
