// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	user "github.com/aussenseiter-VsRB/JHIC-BE/internal/domain/user"
)

// Users is an autogenerated mock type for the Users type
type Users struct {
	mock.Mock
}

// ByID provides a mock function with given fields: ctx, id
func (_m *Users) ByID(ctx context.Context, id string) (*user.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByPosition provides a mock function with given fields: ctx, position, class, jurusan
func (_m *Users) FindByPosition(ctx context.Context, position string, class string, jurusan string) (*user.User, error) {
	ret := _m.Called(ctx, position, class, jurusan)

	if len(ret) == 0 {
		panic("no return value specified for FindByPosition")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*user.User, error)); ok {
		return rf(ctx, position, class, jurusan)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *user.User); ok {
		r0 = rf(ctx, position, class, jurusan)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, position, class, jurusan)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUsers creates a new instance of Users. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsers(t interface {
	mock.TestingT
	Cleanup(func())
}) *Users {
	mock := &Users{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
