// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/aussenseiter-VsRB/JHIC-BE/internal/domain/auth"

	id "github.com/aussenseiter-VsRB/JHIC-BE/internal/pkg/id"

	mock "github.com/stretchr/testify/mock"
)

// SessionRepository is an autogenerated mock type for the SessionRepository type
type SessionRepository struct {
	mock.Mock
}

// ByToken provides a mock function with given fields: ctx, token
func (_m *SessionRepository) ByToken(ctx context.Context, token string) (*auth.Session, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ByToken")
	}

	var r0 *auth.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.Session, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.Session); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, token, userID, expiresAt
func (_m *SessionRepository) Create(ctx context.Context, token string, userID id.ID, expiresAt int64) error {
	ret := _m.Called(ctx, token, userID, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, id.ID, int64) error); ok {
		r0 = rf(ctx, token, userID, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByUserID provides a mock function with given fields: ctx, userID
func (_m *SessionRepository) DeleteByUserID(ctx context.Context, userID id.ID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, id.ID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSessionRepository creates a new instance of SessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepository {
	mock := &SessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
